export const products = [
  {
    id: 1,
    productName: "Enterprise ERP",
    unitPrice: "800K",
    quantityAvailable: 20,
    salesVolume: "16M",
    profitMargin: "60%",
    salesResponsibility: "Collin Wafula",
  },
  {
    id: 2,
    productName: "Enterprise ERP",
    unitPrice: "700K",
    quantityAvailable: 50,
    salesVolume: "35M",
    profitMargin: "50%",
    salesResponsibility: "Namyonga Mary",
  },
  {
    id: 3,
    productName: "Web dev't",
    unitPrice: "500K",
    quantityAvailable: "--",
    salesVolume: "500K",
    profitMargin: "30%",
    salesResponsibility: "Catherine Emmy",
  },
  {
    id: 4,
    productName: "App dev't",
    unitPrice: "800K",
    quantityAvailable: 20,
    salesVolume: "16M",
    profitMargin: "60%",
    salesResponsibility: "Emmy Lutalo",
  },
  {
    id: 5,
    productName: "Enterprise ERP",
    unitPrice: "2M",
    quantityAvailable: 20,
    salesVolume: "4M",
    profitMargin: "60%",
    salesResponsibility: "Collin Wafula",
  },
];
